### ISSUE TITLE
Crie um script em Ruby que permita o usuário digitar vários números. O script acaba quando se digita -9999. Por fim, o script deve apresentar o maior número digitado pelo usuário.

### ISSUE THREAD

**Issue by Mariasimoes1** [exercism/ruby#1055]

**Comment by kotp** [comment]
This sounds like something that could be developed into a concept exercise for V3, not Ruby specific.  Because of the international nature of this project, English is adopted as the official language, to keep everything consistent.

Translation: 

> Create a Ruby program that takes various numbers as given and presents that number or greater.  The input ends when `-9999` is given.

Not directly translated (and perhaps not even translated well).

What are the concepts that you see being used here?  For more information on designing exercises, and where things are going, please see [the readme at v3](https://github.com/exercism/v3).

Related, in terms of a adding mentor notes for a new exercise (existing exercise shown in the graphic animation) is [this area of the project](https://github.com/exercism/website-copy#mentor-notes)

I hope this helps.

**Comment by tuang3142** [comment]
I think we can close this issue @kotp
