### ISSUE TITLE
Amusement Park Improvements. Difference between the call and the error message 

### ISSUE THREAD

**Issue by RoelofWobben** [exercism/ruby#1217]
hello

There is a difference between the call and the error message 

call : 

```
refute Attendee.new(100).has_pass?
```

error message : 

```
RuntimeError: Please implement the Attendee#pass? method
```

**Comment by kotp** [comment]
We might want to keep the `has_pass?` from the prior exercise "Amusement Park", instead of changing it to what is generally idiomatic Ruby, which is to say `pass?`.

**Comment by ntijoh-daniel-berg** [comment]
Looking at the screenshot in slack, `attendee.rb` is used, but the tests are looking for `amusement_park_improvements.rb` 
The files were recently renamed so that the track dev tests worked for concept exercises.

I created a new account and tried the exercise now, and it gave the web editor the correct file.

A workaround is downloading the files using the cli, then you can move your implementation to the correct file. I'm a newbie when it comes to exercism so there might be a better way though.

**Comment by kotp** [comment]
This has changed recently, due to issue #1209 which probably should be reverted.  I did not notice the (presumably scripted) attempt to name the files the same name as the exercise, which is not necessary.  But which is causing some difficulties currently.

**Comment by ntijoh-daniel-berg** [comment]
The tests now uses the file specified in config.json instead of the exercise slug.

I believe the revert has already happened in #1222

**Comment by kytrinyx** [comment]
This has been fixed. Closing.
