### ISSUE TITLE
Savings account

### ISSUE THREAD

**Issue by efgalvao** [exercism/ruby#1237]
In the instructions is said that the interest rate for a balance of 0 dollars is 0% but in the test is asking for another value:
```ruby
    assert_equal 0.5, SavingsAccount.interest_rate(0)
```

**Comment by kotp** [comment]
Effectively multiplying any number by zero gives the effect.  So really the interest rate of a balance of 0 is "undetermined" and can be everything or anything.

**Comment by kotp** [comment]
In context, what is the change that you believe should happen?

**Comment by kotp** [comment]
And of course thank you for bringing our attention to this!

**Comment by efgalvao** [comment]
> In context, what is the change that you believe should happen?

I think the value for the assert should be 0 as is stated in the instructions, right ?
![Screenshot from 2021-09-29 18-07-36](https://user-images.githubusercontent.com/61836657/135348787-8eb3816f-2912-41ba-a7be-a886253dd08f.png)

**Comment by kotp** [comment]
No, because the rate does not change just because the balance is zero.  The amount of interest, not the rate, would be 0.  The test subject would change, in that case.

**Comment by greenlakes** [comment]
I think I have encountered the same issue today.

I am stuck on this task and I believe there is an error in the test:
[](https://exercism.org/tracks/ruby/exercises/savings-account)

I believe my code below is correct solution:

module SavingsAccount
  def self.interest_rate(balance)
    if balance.negative? 
      -3.213
    elsif balance.zero?
      0
    elsif balance < 1000
      0.5
    elsif balance < 5000
      1.621
    else
      2.475
    end
  end

  def self.annual_balance_update(balance)
     balance + balance * self.interest_rate(balance) / 100
  end

  def self.years_before_desired_balance(current_balance, desired_balance)
    years = 0
    while current_balance < desired_balance
      current_balance = self.annual_balance_update(current_balance)
      years += 1
    end
    years
  end
end

still causes one test failure:

FAILED
Test 1
Minimal first interest rate

CODE RUN
assert_in_delta 0.5, SavingsAccount.interest_rate(0), 0.000_1
TEST FAILURE
Expected |0.5 - 0| (0.5) to be <= 0.0001.

I think something is wrong with that particular test since the code works and provides correct answers that are used in other tests that are in turn passing.

Please can you double check and advise.

**Comment by luilver** [comment]
I guess it should be something like:

-3.213% for a negative balance.
0% for a balance of 0 dollars (it neither earns interest, nor is penalised).
0.5% for a positive balance less than 1000 dollars.
1.621% for a positive balance greater or equal than 1000 dollars and less than 5000 dollars.
2.475% for a positive balance greater or equal than 5000 dollars.

**Comment by k3dB** [comment]
I think the confusion is in [this line](https://github.com/exercism/ruby/blob/main/exercises/concept/savings-account/.docs/instructions.md?plain=1#L9) of the instructions.
```Markdown
- 0% for a balance of `0` dollars (it neither earns interest, nor is penalised).
```
I was also puzzled about this line in the instructions versus the [test](https://github.com/exercism/ruby/blob/main/exercises/concept/savings-account/savings_account_test.rb#L5-L7):
```Ruby
  def test_minimal_first_interest_rate
    assert_in_delta 0.5, SavingsAccount.interest_rate(0), 0.000_1
  end
```
The test translates to "a balance of zero gives an interest rate of 0.5 percent because zero is the smallest non-negative number".  This makes sense, but seems contradictory to that one line in the instructions (mentioned above) that makes it sound like "a balance of zero should have a zero percent interest rate".  Of course, to your point, it does not really matter what the percentage is if the balance is zero because zero multiplied by any percentage would still yield no change of the balance.

To be honest, I ended up thinking that it was because the exercise is about `Float`s and `0` is considered an `Integer` (i.e. `0.00` vs. `0`).  Perhaps we either need to add a test specifically for this case, or remove/re-word that line in the instructions to avoid confusion.

The following [line](https://github.com/exercism/ruby/blob/main/exercises/concept/savings-account/.docs/instructions.md?plain=1#L6) in the instructions would cover the test mentioned above, so perhaps that line about "a balance of `0` dollars" can just be removed from the instructions, or re-worded in a later part of the instructions about calculating the desired balance.
```Ruby
- 0.5% for a non-negative balance less than `1000` dollars.
```

**Comment by kotp** [comment]
I think it could just be removed.  See the discussion happening in a PR that addresses this same area.  #1239

**Comment by efgalvao** [comment]
I agree it could be removed, I understand that 0 is the firs non-negative, but the last line saying 0 dollars  should return a interest rate of 0% is misleading.

**Comment by kotp** [comment]
The last line saying 0 dollars should return an interest rate of 0.5% would be correct, the other is wrong, perhaps a typographical error.

**Comment by caiangums** [comment]
Hey! I know I'm new here but I also got confused with this exercise. As the description of the exercise states `0% for a balance of 0 dollars` and we are asked to actually implement the `interest_rate()` function, it is clear that if we pass the `balance = 0` the return should be `0`.

I understand, and agree that any number multiplied by `0` is equal to `0` but conceptually for implementing the `interest_rate()` function and sending to it `0`, as described in the exercise it should return `0%` instead of `0.5%`.

My suggestion is to remove that last line from the exercise description and let it implicit that the balance `0` should return interest of `0.5%`. With this, the test is also maintained 😄

**Comment by kotp** [comment]
Why do you believe that the 0 should trigger an interest rate change?  The interest rate could be anything, the accrual will still be 0?  The rate would still be whatever the rate is.  This is what is confusing to me.  If I have a fixed interest rate on my account, let's say when I first opened up my savings account years ago, at 5% compounded… if my balance went to 0, my interest rate for the account remained the same.  My accrual was 0, but the rate was unchanged.

Line 9 of the `instructions.md` file should indeed be corrected.  It should not return 0% unless we were asking what percentage of a return do we receive, as opposed to the rate.  It could be removed, as it is incorrect.

@efgalvao would you like to make the change in a pull request?  Reference (or "closes: issue number") this issue here so it automatically will be closed when it comes in?
