### ISSUE TITLE
test is wrong here  [triangle] 

### ISSUE THREAD

**Issue by RoelofWobben** [exercism/ruby#1262]
in triangle there is this test 

```
  def test_sides_that_violate_triangle_inequality_are_not_scalene_even_if_they_are_all_different
    # skip
    triangle = Triangle.new([7, 3, 2])
    refute triangle.scalene?, "Expected 'false', triangle [7, 3, 2] is not scalene."
  end
```

but that test is wrong 

you can test the violation like this 

```
   side1, side2, side3= sides
    side1 + side2 <= side3 || side1 + side3 <= side2 || side2 + side3 <= side1
 ```

side1 + side2 <= side 3 so 7 + 3 <= 2       False 
side1 + side3 <= side2 so 7+ 2 <= 3        False 
side2 + side3 <= side1 so 3 + 2 <= 7      True 

so this one do not violate the principles

**Comment by SleeplessByte** [comment]
You've given the following formula:

```ruby
a, b, c = sides
a + b <= c || a + c <= b || b + c <= a

# Or with your naming:
side1, side2, side3 = sides
side1 + side2 <= side3  || side1 + side3  <= side2 || side2 + side3  <= side1
```

With the following results:

```text
7 + 3 (10) < 2   # false
7 + 2 (9)  < 3   # false
3 + 2 (5)  < 7   # true
```

And then said 

> so this one do not violate the principles

However, the method that would have this formula, would be called `violates_inequality?`

```ruby
def violates_inequality?
  a, b, c = sides
  a + b <= c || a + c <= b || b + c <= a
end
```

Meaning that if _one_ of the clauses is true, it is a violation. If you wanted to test that it did NOT violate the inequality, you'd have to write:

```ruby
def satisfies_inequality?
  a, b, c = sides
  a + b > c && a + c > b && b + c > a
end
```

...which would return `false`, because the clauses would be `true`, `true` and `false`, thus making the entire thing return `false`.

**Comment by RoelofWobben** [comment]
if I change it to that a lot of more tests are failing
