### ISSUE TITLE
[tests] Microwave exercise test suite have errors.

### ISSUE THREAD

**Issue by JeremasPosta** [exercism/ruby#1268]
# Problem explanation
Some of the tests of the Microwave exercise are wrong.

Since the objective is to turn seconds into a digital clock form, it is wrong that the input of 100 seconds expects an answer of a single minute instead of 01:40.

# Actual behavior 
Several tests fail when they shouldn't.
![image](https://user-images.githubusercontent.com/60799999/142773894-653dd5ac-7849-4a8f-bfd3-7b14d9faa565.png)

# Expected behavior
The test suite must fit the exercise requirements.

```
100s => 01:40
101s => 01:41
159s => 02:39 
```
This error repeats in other tests in the same file, but not in all.

I believe that the initial idea was to test one minute, one minute and a sec, one minute and 59 sec, etc, so I will patch the test to fit the test name, and not the ```assert_equal```.

# File affected

https://github.com/exercism/ruby/blob/d2527fb6b99d4cfce687fb41875d71f30bdc22e6/exercises/practice/microwave/microwave_test.rb

**Comment by JeremasPosta** [comment]
Maybe I'm getting this wrong and that's all...

**Comment by kotp** [comment]
100 is 1 minutes 0 seconds, where 90 is 1 minute 30 seconds.  Just like
it works on many microwaves.  And this is stated in the _Instructions_
tab as shown [here][1].

So there is only one input, and it is not determined to be minutes until
the inputs are parsed.  100 being 1:00 seconds, 99 being 1:39.  This is
how it works for many models of microwaves.

The expected behavior for these inputs is as shown on the right hand
side:

| input | expected |
|----|----|
|100|1:00|
|101|1:01|
|159|1:59|

The tests should be enforcing this expectation.

[1]: https://github.com/exercism/ruby/blob/d2527fb6b99d4cfce687fb41875d71f30bdc22e6/exercises/practice/microwave/.docs/instructions.md

**Comment by JeremasPosta** [comment]
But the instructions doesn't especify that 100 are equal a minute. Only
that 90sec is 1.5 minute, which is true. Why I should assume that 100 sec
are not 01:40?

**Comment by kotp** [comment]
Because the README/Instructions are BOSS level, while the tests specify
the details.  If the solution fails the tests, and do not contradict the
README, then it is probably per design.

However that does not mean that it can not be discussed or changed.  It
probably would need to be discussed in [problem-specifications][1] where
the exercise lives for many different tracks.

[1]: https://github.com/exercism/problem-specifications

**Comment by JeremasPosta** [comment]
I understand.  Maybe a table like the one you shared early, should be on the Readme.
This issue will be closed.

**Comment by kotp** [comment]
Feel free to create an issue in [problem-specifications][1] where it can be
discussed, and a PR can be created so every track can take advantage if/when it
comes in.

[1]: https://github.com/exercism/problem-specifications/issues
