### ISSUE TITLE
Kindergarten Garden may be harder than defined

### ISSUE THREAD

**Issue by edgerunner** [exercism/ruby#1328]
This exercise was marked as "easy" but I'm surprised to see that it involves dynamically constructed / metaprogrammed method names. As easy as doing that gets in Ruby compared to other languages, I'd still consider that at least a "medium".

`method_missing` turned out to be the easiest way out I could suggest to one confused mentee, and then I went through the exercise myself to get feedback from another mentor, for which @kotp gave some solid feedback.

I think we need to bump up the difficulty tag for this exercise in the Ruby track, and include some pointers about metaprogramming in the instructions, as well as some mentoring advice on the possible approaches. As a bonus, this could also become the concept exercise for "Metaprogramming"

Another possible approach is to change the tests, so that the implicit requirement of accessing student gardens through dynamic methods is no longer there. The difficulty stays "easy" and the focus of the exercise stays on zipping enumerables.

Which do you think is a better approach?

**Comment by kotp** [comment]
I think that the planets exercise is the best exercise for introducing metaprogramming, because of the pattern presented, rather than this exercise.  So as far as the first exercise goes, perhaps it is not the one.

But. this is a practice exercise, not a concept exercise.  So with the idea of "practice" rather than "concepts", while I think that Hamming is perfect for introduction to `zip`.

I am open to moving this to "medium" though, along with information about metaprogramming, hopefully with a few different options.  I have noticed that many solutions use `define_singleton_method`, some use `method_missing` (which is good, but many are only half completed, missing the `respond_to_missing` that makes the solution more complete).

**Comment by kotp** [comment]
I think that the planets exercise is the best exercise for introducing metaprogramming, because of the pattern presented, rather than this exercise.  So as far as the first exercise goes, perhaps it is not the one.

But. this is a practice exercise, not a concept exercise.  So with the idea of "practice" rather than "concepts", while I think that Hamming is perfect for introduction to `zip`.

I am open to moving this to "medium" though, along with information about metaprogramming, hopefully with a few different options.  I have noticed that many solutions use `define_singleton_method`, some use `method_missing` (which is good, but many are only half completed, missing the `respond_to_missing` that makes the solution more complete).

**Comment by kotp** [comment]
If you do not, it looks like @NeimadTL will pick it up tomorrow.

**Comment by edgerunner** [comment]
@kotp just saw it all. Can't do it now but I can possibly keep an eye on @NeimadTL's progress and offer remarks.
