### ISSUE TITLE
TwoBucket - possible error in test suite

### ISSUE THREAD

**Issue by loranger32** [exercism/ruby#1450]
Hi,

I think there could be an issue with the tests in `two buckets` ruby exercise.

In the test `test_measure_using_bucket_one_of_size_2_and_bucket_two_of_size_3_start_with_bucket_one_and_end_with_bucket_two` (starting line 45) the expected number of moves is set to `2`, but I'm wondering if it shouldn't be `4`. All my other tests pass and that's the solution I get when solving the exercise on paper.

Out of curiosity I've checked the same exercise in the Elixir track and the same test also sets the expected number of moves to `2`, so, it's maybe just me missing a nice shortcut to get it in 2 moves :-).

Thanks for your time.

**Comment by kotp** [comment]
Please request a mentor for the Ruby exercise, so that it can be determined there.  This is a great way to take away the "it's maybe just me missing…" since it will have been hopefully discussed and verified by a mentor.

If you are using the command line tool, you can submit it, even if it is failing.  If you are using the web editor, you can hard-code the solution in order to get that failing test to pass (but comment it as such, since, if you then say "there is a failing test", that would not be true.

**Comment by loranger32** [comment]
Ok, thanks for your answser, I will request mentorship.

**Comment by kotp** [comment]
No problem.  Glad you found it!
