### ISSUE TITLE
Armstrong exercise tests confusion

### ISSUE THREAD

**Issue by imechemi** [exercism/ruby#1555]
The test does not inform what method should be implemented. Can someone please confirm if the tests are still correct? 

```
def test_single_digit_numbers_are_armstrong_numbers
    skip
    assert_includes ArmstrongNumbers, 5
  end

```

```
TypeError: wrong argument type Integer (expected Module)

Traceback (most recent call first):
    Line 7:in `test_zero_is_an_armstrong_number'
```

**Comment by iHiD** [comment]
It's a bit weird, but the tests are correct. You can write the code like this.
```
class ArmstrongNumbers
  def self.include?(number)
    #...
  end
end
```

I think we should add a stub. @ErikSchierboom Do you agree?

**Comment by ErikSchierboom** [comment]
I 100% agree. In general I think that stubs should be added to all practice exercises, on the condition that it doesn't unnecessarily restrict the student to certain solutions. In this case, the interface to implement is fixed and thus there is no benefit to defining the signature from scratch. As Ruby has Learning Mode, it is there that students can practice defining function signatures.

**Comment by kotp** [comment]
Summary: Did we identify that this is an error and not a failed test?  We may be missing a test to inform the student that we need to write a class, it is not reporting a deficiency in a missing `include?` method.  The test itself does inform, but the message given was not about the method.  Perhaps we are missing a test, so it fails, instead of causing an error, in this situation.

> I 100% agree. In general I think that stubs should be added to all practice exercises, on the condition that it doesn't unnecessarily restrict the student to certain solutions.

Even if the stubs are given, it does not mean that it is a "given" in that the students are not allowed to delete the stub and write it in another way.  It also does not restrict students from throwing the stubbed material out, in case they want to write it in another way, so I think stubs are fine.  This is not the only way to get this method to pass (the `def self.include?(argument)` while it is probably  a first reach)

> I think we should add a stub

The tests itself means that the student almost has to know what "assert_includes" means, in that it alludes to calling the method `include?` which really is not intuitive.  They must have some knowledge of the testing framework to know this.

Do we give them that information anywhere?

Are we missing information that should be given to the student in `HELP.md` where we give information about what the minitest assertions are using to check underneath the hood?  How would they know given the failing message.  We can do this in a test message, so the test may be lacking communication.

I think we are not checking that the constant `Armstrong` exists and instead letting the tests fail to give some hint.  And then the response is that a module does not exist, which is not required, but could be _a_ solution to what the tests need to continue, to finally get to the information that the `include?` method does not exist, which should bubble up as things are progressed.

So, my question is "do we let the student learn how to read the error messages when something comes up like this, or do we hold their hand for, as @ErikSchierboom suggests, all practice exercises.

Perhaps stubs are not necessarily the best answer (as it can hide a deficiency that should be known, but might end up being a hand waved away thing that they have to know later in life).  We might be missing a fundamental test here to help the student get a better test failure message here.

I write this, because the method not being written here is not the problem coming from the errored test, since the test did not fail, but instead is an error.

If we had a test that suggested that we need the constant Armstrong, which could be a class or a module, (or not), then the error would not happen, but a test failure instead.

**Comment by kotp** [comment]
> I think this whole `include?` thing is a big distraction from the actual exercise. The only reason we have this is because Rubocop automatically updated the files - it's not by design: [3129539](https://github.com/exercism/ruby/commit/312953999b85b02c0769f327b33a5124b8b947fb)

A fairly good argument to not have a "robot" update things automatically.  If that is the only reason.  It should have been that plus another reason, really.

> I think this whole include? thing is a big distraction from the actual exercise.

Should we remove the test then?

Stub would be less disruptive all around, for sure.

**Comment by iHiD** [comment]
Added in https://github.com/exercism/ruby/pull/1556
