### ISSUE TITLE
Create stubs for exercises.

### ISSUE THREAD

**Issue by Insti** [exercism/ruby#541]
Should we create stub files for exercises?

These would be empty or partially complete solution files.
For example the "hello-world" exercise requires that the `hello_world.rb` file exists.

I think this would help people get started.

**Comment by Insti** [comment]
See https://github.com/exercism/discussions/issues/114 for a link to discussions other tracks have had about the question of stubs.

**Comment by kotp** [comment]
Any empty file that is required due to being required in the test file, I think that is suitable.  Even better, with the BookKeeping module that is required for the exercises where the tests are generated, already written... Other than that, having the exercise started with a class or module or constant is not such a great idea... unless the exercise is more about performance, refactoring or something similar.

**Comment by behrtam** [comment]
We (python – https://github.com/exercism/xpython/issues/272) are facing the same question. Did you come up with a solution in a different place than this issue?

**Comment by kotp** [comment]
I think this is current discussion, @behrtam.

**Comment by Insti** [comment]
I think we should add stub files.
Some of the early ones can have useful starting templates setting up the classes and methods. The later ones can be empty.

**Comment by F3PiX** [comment]
I think this would be great - for the TwoFer exercise only. With a test added that shows that a file is  present. 
For other exercises, knowing how to create a file, is part of the language fluency, and I don't think it should be present.

**Comment by Insti** [comment]
I know how to create files, creating one for every exercise is a meaningless chore that could be solved by adding the necessary file.

On a real project you also don't start with a pre-built test suite..

So perhaps explicitly *not* including the template on the third(?) problem and documenting that this is intentional would solve both our goals?

**Comment by pgaspar** [comment]
I _think_ I like this idea. I saw it on the Elixir track and it gave me a bit more confidence on the initial exercises.

> For other exercises, knowing how to create a file, is part of the language fluency, and I don't think it should be present.

I understand this point though. I've had discussions around how classes are structured from people who were confused by the how the tests were setup on TwoFer (thinking specifically about [this submission](https://exercism.io/mentor/solutions/080f4d5490944ef8b8e2c0f5f7dbf3c4)).

I think it's useful to have a bit more hand-holding on the first exercises though. And if someone has questions about how tests are setup they can at least understand what we expect them to do on those initial exercises.

**Comment by iHiD** [comment]
I'm a big fan of doing this everywhere. I think it just helps make things really clear and easy. The less need for any command-line interaction, the better. One thing to consider is that the hello-world tests that are walkthrough-y presume the file won't be created, so I don't know if we need to change that. (cc @kytrinyx).

**Comment by iHiD** [comment]
Widening this to the whole of exercism: https://github.com/exercism/exercism/issues/4789

**Comment by ErikSchierboom** [comment]
> I know how to create files, creating one for every exercise is a meaningless chore that could be solved by adding the necessary file.

To me, this was one of the key reasons why we introduced it. Creating a file is easy, and often tedious. I do agree that at some point we can expect people to know how to do this themselves. Note: does creating a file teach fluency?

**Comment by kotp** [comment]
Creating a file is no more teaching fluency than creating an array or list or hash or map or string.  But it is part of knowing how to get around and feeling comfortable.  I see a lot of programs in the wild that creates files, so yeah, I think it is part of it.  Of course, you can choose to create files outside of that language, and then it teaches promotes fluency in the environment in which you need files.

**Comment by iHiD** [comment]
We're not talking about creating a file using Ruby though. Most people use "File->New" in their editor to achieve this.

**Comment by ErikSchierboom** [comment]
Sorry for the confusion @kotp, I was referring to the fact that creating a `x.rb` file in the exercise's directory is not part of a language's fluency. The actual creation of a file using Ruby functions of course _is_.

**Comment by kotp** [comment]
No, but we are talking about creating a file __for__ Ruby.  Being able to take the communication that is given from Ruby, knowing that it is looking for a file that isn't there, identifying that it is either the wrong file that is being asked for or that the file needs to be created (or is unreadable, etc) is part of that skill that is needed.  Being able to respond to that feedback without stumbling, is an indicator for fluency.  (Though that fluency may extend below Ruby to the operating system).

**Comment by kotp** [comment]
I am for stub files early on, as a person new to the language, I don't really need to be pressed for learning to read the error messages for even getting started... but after I see the pattern of what is needed, I would hate to finish up here, and get stopped with an error message that I can't read because I did not see it before, when I had plenty of chances to learn that here.

**Comment by kytrinyx** [comment]
Early on I was quite adamant that people should have to create the file themselves at some point, and that is because I watched people do TDD and not understand the error message. The error message would pop up, their eyes would glaze over and they'd reflexively try to make it go away, without knowing exactly how.

Now I don't feel strongly about it. I feel like we have a much better understanding of what Exercism is for, and this does seem like make-work that gets in the way of that more than it helps.

**Comment by kytrinyx** [comment]
Closing as solved. All exercises now have stub files.
