### ISSUE TITLE
Document test regeneration.

### ISSUE THREAD

**Issue by Insti** [exercism/ruby#717]
We need to document the test re-generation procedure so that it is possible for new contributors to do.

Future goal: automate it.

**Comment by kotp** [comment]
Once test version goes away, automation should be easier.

Here is what I did to find out which ones needed to be updated:

```bash
cd Project/Exercism/problem-specifications
git checkout master
git pull origin master
cd ../ruby
git pull origin master
bundle exec bin/generate -f -a
git status
git reset --hard
```

This lets me see any changes in the project from the generation of the test files.

Then I needed to find out why the changes happened, and I did so by looking at the history of the `exercises/_exercise-name_/canonical.md` to find what caused the change.  Find the same description in the pull requests on problem-specifications, to get a reference number.

Create a new pull request for each file changed, and generate the test by doing `bundle exec bin/generate -f hamming` for example, with no update in the test.

Soon generations will be without version update by default, then this command will change, incrementing the version number will need to be explicitly requested, rather than asking not to.

**Comment by Insti** [comment]
The procedure has changed a little from the above.

* The generator `--freeze` option has been replaced by `--update` (See #737)

* Pull request naming convention, please use `slug: regenerate tests`
e.g.
> two-bucket: regenerate tests

* There probably needs to be a paragraph or two about when to update the BookKeeping version. (This may be documented already in the README.md?)


(This might be useful information for you @rpalo )

**Comment by rpalo** [comment]
I'll get on it!
