### ISSUE TITLE
documentation: How to checkout problem-specifications

### ISSUE THREAD

**Issue by Insti** [exercism/ruby#754]
The documentation on generating test suites: https://github.com/exercism/ruby#generated-test-suites

> Generated exercises depend on the the shared metadata, which must be cloned to the same directory that contains your clone of the ruby repository:

**Task:**

Add a line or two if documentation explaining this a bit more and including the git commands to checkout (and/or update) the problem-specifications repository.

File to edit: https://github.com/exercism/ruby/blob/master/README.md

**Comment by architapatelis** [comment]
@ Insti I am not sure if this is what you are looking for when you say: git commands to checkout (and/or update) the problem-specifications repository. But, here is an outline of some of the git commands I used to get started with `exercism`. I hope it helps whoever plans of completing the task

`$ mkdir exercism`
`$ cd exercism`
fork [exercism/ruby](https://github.com/exercism/ruby)
fork [exercism/problem-specifications](https://github.com/exercism/problem-specifications)

locally clone both `ruby` and `problem-specifications`:

```
$ git clone https://github.com/YOUR-USERNAME/YOUR-RUBY-REPOSITORY
$ git clone https://github.com/YOUR-USERNAME/YOUR-PROBLEM-SPECIFICATIONS-REPOSITORY

```
Periodically, you'll need to sync these local repos with the upstream repos, in order to get the latest changes. GitHub has instructions for doing this:

1. [Configuring a remote for a fork](https://help.github.com/articles/configuring-a-remote-for-a-fork/)
2. [Syncing a Fork](https://help.github.com/articles/syncing-a-fork/)
3. Once you have synced your local `master` branch with the `upstream/master` branch, you will need to `$ cd working-local-branch` and perfrom `$ git rebase master`

You might have to fix some merge conflicts at this point. Once that is done, your local branch it up-to-date with the upstream/master


**Other Suggestion:**

I also want to mention something related to this topic and that is instructions on how to [implement an exersice from specification](https://github.com/exercism/docs/blob/master/you-can-help/implement-an-exercise-from-specification.md). I think the [README.md](https://github.com/exercism/ruby/blob/master/README.md) file should have a link to it somewhere, it would help those who plan on contributing by creating a new exercise. 

When I was trying to implement a new exercise, I read [READMEs are constructed using shared metadata](https://github.com/exercism/ruby#readmes), but how exactly is that done? I had to go from one place to another to figure out how I am supposed to generate a README file. 
So, maybe within `implement-an-exercise-from-specification.md` you can have better instructions on how to install and use `configlet`, 

when I was trying to set it up, I didn't really find the correct instructions so I ended up following the same directions as the ones for [installing exercism CLI](http://exercism.io/clients/cli/linux)

like so:

```
$ tar -xzvf configlet-linux-32bit.tgz
$ mv configlet ~/bin/
$ export PATH=$HOME/bin:$PATH
$ echo 'export PATH=$HOME/bin:$PATH' >> ~/.bashrc

```

I am not sure, if this is the right way to do it but it worked for me. I am fairly new to coding so I might be the only one that struggled to figure out how to generate a README.md file using `configlet generate . --only exercise-name`. However, in case I am not the only one, then I think if the instructions are more clear it would help developers who are new to exercism.  I hope you find this feedback useful.  :)

**Comment by Insti** [comment]
Thanks @architapatelis that is useful feedback. :heart:

**Comment by son-vyas** [comment]
@Insti  I would like to give this a try.  Can you assign me this task?

**Comment by Insti** [comment]
Sure @son-vyas, go ahead and make the changes and submit a pull request.
Let us know if you need any help.

**Comment by son-vyas** [comment]
@Insti I have submitted the pull request. Please review and let me know suggestions , if any

**Comment by kotp** [comment]
@son-vyas Any word on this?

**Comment by son-vyas** [comment]
@kotp, I will surely look at what you have suggested and will update the Readme.md soon
