### ISSUE TITLE
change: README doesn't match the test data

### ISSUE THREAD

**Issue by llenk** [exercism/ruby#873]
The README on the website and the one that is downloaded says output should be of the form [4, ...] for 4 pennies etc. The tests that are downloaded have the output should be of the form [1, 1, 1, 1, ...] for 4 pennies etc.

**Comment by Insti** [comment]
Source of the `change` README: https://github.com/exercism/ruby/blob/master/exercises/change/README.md

The `change` readme and test data are based on the common version in the [problem-specifications repository](https://github.com/exercism/problem-specifications)

It looks like this issue is also present there.

The right thing to do is to update the description in the problem-specifications repository and then regenerate the readme over here.

Can you create an issue in that repository? 


(Another alternative is to update the test generator to generate tests that match the Readme, but I think the format we have is more sensible than the one described in the Readme)

**Comment by Insti** [comment]
Thanks for raising this issue @llenk :heart:

**Comment by Insti** [comment]
Sorry, I didn't look at this closely enough.

The README file was recently fixed and updated: https://github.com/exercism/ruby/commit/4e8511735390b5b2d83cf6ab668ebcf03397c1f3#diff-4abcb5f56eb705fba2773452cbbacabfR9

So the current version is correct.

The problem you are seeing is a symptom of this issue: https://github.com/exercism/exercism/issues/4219 which means you are forever stuck on the version that you initially downloaded.

:disappointed:

**Comment by F3PiX** [comment]
@insti Can we close this?

**Comment by kotp** [comment]
Closing, as it will still be here to re-open if @llenk needs attention on this.
