### ISSUE TITLE
New advanced exercise: Add Grep

### ISSUE THREAD

**Issue by F3PiX** [exercism/ruby#946]
The start of the Ruby Track got a lot of attention in the previous months. It's time to give the end of the track a bit of Tender Loving Care as well. After Luhn and Clock, there's a lot more advanced features to explore. 
One thing that is missing, is Importing and reading a file. 

Problem Specifications has Grep: https://github.com/exercism/problem-specifications/blob/5326cf2b32fd5df77cda3ade20d088d9a928b8b3/exercises/grep/canonical-data.json

Looks like a good candidate to add as a side, and maybe to be promoted to core later on.

Anybody feel like implementing it for Ruby?

**Comment by pgaspar** [comment]
Nice, that's an interesting exercise. I am interested in implementing it as specified, but I'll likely take to the end of the week to have something up because I'm expecting a busy week at work. Lmk if that's ok!

PS: I don't know if you are thinking about this as a "scripting" exercise, but my suggestion is for us to add it as it's specified on the canonical data and then eventually think about scripting after the initial implementation is merged.

**Comment by F3PiX** [comment]
Great! :tada: No hurries, of course.

And yeah, added as specified was what I had in mind too. (Looks like scripting to me, so maybe it's just a definition that we have to straighten out?)

**Comment by pgaspar** [comment]
> Looks like scripting to me, so maybe it's just a definition that we have to straighten out?

Interesting... Yeah, what I see in the specs is something that results in something like:

```ruby
Grep.grep(pattern: 'Agamemnon', flags: [], files: ["iliad.txt"])

# or

Grep.grep('Agamemnon', [], ["iliad.txt"])
```

Returning the expected string.

However, after reading `description.md` I'm not so sure anymore, since it specifically mentions things like:

> If we were to call `grep "hello" input.txt`, the returned string should be [...]

Even so, from the implementations I've seen in other tracks everyone implements this as I'm suggesting - with no real terminal interface (ARGV, etc). Some examples:

* [Java](https://github.com/exercism/java/blob/a0f91066641f672d1d77b2a3f07df3732c9096b4/exercises/grep/.meta/src/reference/java/GrepTool.java#L12) - [spec](https://github.com/exercism/java/blob/a0f91066641f672d1d77b2a3f07df3732c9096b4/exercises/grep/src/test/java/GrepToolTest.java)
* [Elixir](https://github.com/exercism/elixir/blob/de905583512ed9d472f47eb3a319df1d0a04e5a9/exercises/grep/example.exs#L82) - [spec](https://github.com/exercism/elixir/blob/de905583512ed9d472f47eb3a319df1d0a04e5a9/exercises/grep/grep_test.exs)
* [Python](https://github.com/exercism/python/blob/a83f53697a1a213967838a78b86f2b358727d76f/exercises/grep/example.py#L45) - [spec](https://github.com/exercism/python/blob/a83f53697a1a213967838a78b86f2b358727d76f/exercises/grep/grep_test.py)

There is IO, but there's no handling of ARGV.

That's what I'm hoping to do :+1:
