### ISSUE TITLE
anagram: clarification for the definition

### ISSUE THREAD

**Issue by joaomarcosgris** [exercism/ruby#965]
While I was solving Anagram, I was very confused by the last test because I thought that the same combination of characters can be an anagram. I suggest putting a comment in the problem statement. Maybe "listen is not an anagram of listen". What do you think?

**Comment by kotp** [comment]
This issue may end up moving over the [exercism/problem-specifications](https://github.com/exercism/problem-specifications), but if not applicable Exercism wide, we could make the changes here.

**Comment by F3PiX** [comment]
AFAIK a common description of an anagram is that it is letters shuffled to form a _new_ word. I like that the tests cover the case where the _same_ word is not considered an anagram. There may be other definitions, but as I understand your comment, @joaomarcosgris, you're not disputing the definition, right?
In that case, I'd prefer not to change the description. I don't think that the description should cover all the edge cases that the tests cover. 

Otoh, ideally the tests should build up reasonably. @joaomarcosgris , Did you need to rewrite your solution because of the last test only? Or did you rather have to add something, like an extra clause?

**Comment by kotp** [comment]
I did not see a definition in the exercise to dispute.  Other exercises defines the core thing:

Isogram states:

> An isogram (also known as a "nonpattern word") is a word or phrase without a repeating letter, however spaces and hyphens are allowed to appear multiple times.

Pangram exercise states:

>  A pangram (Greek: παν γράμμα, pan gramma, "every letter") is a sentence using every letter of the alphabet at least once

Yet anagram states only:

> Given a word and a list of possible anagrams, select the correct sublist.

Anagram exercise doesn't give any definition in the description, It only gives an example of a list of candidates.  

I vote to give an orientation level description.  This would make this match the similar word exercises.

**Comment by F3PiX** [comment]
That is really helpfull research. I totally agree. 

@joaomarcosgris And I'm still interested if the last test forced you to choose a different approach.

**Comment by joaomarcosgris** [comment]
My initial approach was to initialize a `@chars` instance variable with characters in the word given in sorted order. 

After having stumbled in the last test, I was forced to change my approach by sorting the chars during each test.

So yeah, I'd say it forced me to choose a different approach.

**Comment by F3PiX** [comment]
Thanks for clarifying! 

Would  you prefer to open an issue on the Problem Specification repo yourself? Or would you like me to take over from here? I'm happy with both.

**Comment by joaomarcosgris** [comment]
I prefer to do it myself. So I can practice collaborating in open-source software :)

**Comment by F3PiX** [comment]
Awesome! 👍

**Comment by joaomarcosgris** [comment]
Fixed by https://github.com/exercism/problem-specifications/pull/1529
