### ISSUE TITLE
flatten-array: Indicate that it is not allowed to use method from stdlib

### ISSUE THREAD

**Issue by joaomarcosgris** [exercism/ruby#966]
I propose stating it clearly that is not allowed to use `Array#flatten`, like in the leap exercise:

> If your language provides a method in the standard library that does this look-up, pretend it doesn't exist and implement it yourself.

**Comment by F3PiX** [comment]
Hi @joaomarcosgris Thanks for bringing this up! 

It should not be stated in the description because it is _meant_ to use the Array#flatten method.

I know that mentors sometime ask students to implement it themselves, but as it is one of the very first exercises in the track (unlocked by Hello World, so even before the first mentored exercise), it is really meant to be a 'warming up' exercise. Also, as Exercism is meant to learn what the general libraries has to offer, why should we ask students to _ignore_ methods that already exist? 
(And yes, Leap does that too, I know. I'm not happy with that either.)

@exercism/ruby I feel we should remove this exercise entirely from the track, but I've been hesitating because we don't have a few nice and easy exercises after Hello World. It's currently Flatten Array and Gigasecond only. 

. _With_ using the `Array#flatten` method, it's actually too easy for the Ruby track. As an 'implement it yourself' we should move it up in the track (a bit).

One other option for replacement would be Resistor Color 1. We don't have that implemented because it's also too easy, but at least it is less ambiguous for mentors. Maybe a better choice unless we have something else?

I see 3 options:
- Add Mentor Notes to explain to not ask for 'DIY implementation' when students start with the Array#flatten solution
- Move Array#flatten up (a bit) in the track _and_ implement Resistor Color #1 as a replacement. 
- Find a better replacement (I'm not aware of one within ProbSpec.)
 
Thoughts?

**Comment by bernardini687** [comment]
Hello!

As a follower of the exercises, I did find the *flatten-array* exercise to be ambiguous. I thought that using `Array#flatten` meant cheating but following @F3PiX line of thought about it being a warm up exercise, now it makes sense. Still, I think it's confusing and as a user I would have probably preferred it to be more challenging (explicitly asking for a DIY implementation) but further in the track.
So option 2 would be reasonable to me 👍

**Comment by yyyc514** [comment]
> I thought that using Array#flatten meant cheating

I've always assumed this also (and told students the same).  I didn't see the point of a one-liner that uses just two library methods.  I guess if I'd understood how early this was on the track perhaps it makes more sense.  **The UI really should expose this more to mentors (where in the track an exercise is).**

>  Still, I think it's confusing and as a user I would have probably preferred it to be more challenging (explicitly asking for a DIY implementation) but further in the track.

I can't recall any students that I've asked for a manual solution who had much trouble, perhaps I've just been lucky...?  So I agree this would be a lot better moved later in the track and made a more advanced exercise.

**Comment by F3PiX** [comment]
I totally agree with you that the UI should expose the position of an exercise in the track. 💯 

> I can't recall any students that I've asked for a manual solution who had much trouble
I'm also thinking of the mentors, not only the students.  Did you find it _fun_ to mentor?

**Comment by yyyc514** [comment]
Treated as a more advanced problem (where you have to implement it from scratch) it's reasonably interesting to mentor.  I wouldn't really choose to mentor it "as-is" as a "early" exercise.  I don't get much enjoyment out of exercises where I just tell someone which method to call.

**Comment by kotp** [comment]
> I don't get much enjoyment out of exercises where I just tell someone which method to call.

I don't usually tell them which method to call, but will point them to the suggestion of at least reading the method names on objects that they use, as for me, it helps to have seen the "word" and starts to build a vocabulary, even if I don't know the details of that "word" yet.

From the terminal...

```sh
ri Array
```

Or even seeing a word that jumps out at you in relation to what you are trying to solve:

```sh
irb --simple-prompt
>> Array.intance_methods.sort
=> # list of method names sorted
```

**Comment by yyyc514** [comment]
> It should not be stated in the description because it is meant to use the Array#flatten method.

Could a hint be added to the instructions then that it's possible (and permissable) to do this using built-in library methods so at least all the mentors are clear in the future that that's allowable?

**Comment by kotp** [comment]
I would put it in the mentor notes, rather than in the instructions.  At all points, Students should know they can use the methods available unless explicitly directed to not do so.

**Comment by yyyc514** [comment]
> At all points, Students should know they can use the methods available unless explicitly directed to not do so.

Lately doesn't seem very many are using the methods though - do you think they want to do it the hard way or just don't know there is an easy way?  I'm going to start asking them. :-)

**Comment by F3PiX** [comment]
My bet is they heard in tutorials that they shouldn't use the standard lib to solve programming problems. :-) I'd be interested to hear the answers Josh!

**Comment by F3PiX** [comment]
@joaomarcosgris I'd like to close this issue, unless you think it isn't finished?

Recap:
The Flatten Array exercise is not the ideal starter after Hello World, because it't too easy with the built-in Ruby method, and it's not cool to start the track with DIY implementing core lib methods. 
We're going to add Resistor Color (#1) as a replacement. 
We still need to decide if we remove Flatten Array entirely from the Ruby track.

**Comment by joaomarcosgris** [comment]
Yes! I think it is better to close it. Thanks for the recap!
