### ISSUE TITLE
alphametics: exercise directory contains two solutions

### ISSUE THREAD

**Issue by petertseng** [exercism/ruby#986]
The alphametics exercise directory in this track contains two solutions, alphametics.rb and alphametics_compact.rb. It is the only exercise that has two solutions, demonstrated by:

```
$ ls */.meta/solutions/*.rb | cut -d/ -f1 | uniq -c | sort -nr | head -3
      2 alphametics
      1 zipper
      1 wordy
```

The test runner will only ever run alphametics.rb due to https://github.com/exercism/ruby/blob/master/lib/tasks/exercise.rb#L26, so alphametics_compact.rb is never run. As a result, it's not possible to say anything about whether alphametics_compact.rb is maintained.

**Comment by F3PiX** [comment]
Related: #849, resulting in PR https://github.com/exercism/ruby/pull/883
Looks like the `*_compact` version was meant to replace the other one.
> This PR should only show one file (the example solution) changed.

**Comment by guygastineau** [comment]
So there should be a PR that removes `alphametics.rb` and then renames `alphametics_compact.rb` to `alphametics.rb`?

**Comment by F3PiX** [comment]
I think so. _If_ the new one proofs to be a more efficient solution. I'm not sure if that was still unclear.

**Comment by guygastineau** [comment]
As I was traversing the spider web of past issues and PR's about this I believe I saw that it is more efficient.  I suppose we can always test it ;)

**Comment by Insti** [comment]
Having multiple solutions in the solutions directory has always been an intended feature.

This allows for multiple reference solutions to exist that optimise for different things.
speed/readability/recursion/iteration/no conditionals/etc

Only one of them (the one with the name matching the slug) needs to be run as part of the test suite to verify that the tests are all passable.

**Comment by F3PiX** [comment]
O thanks @Insti ! I didn't know that that was the intention. 👍 

In that case, I agree that we shouldn't remove/replace. But it would be nice if this would be more clear. Such as: change the file name to `alphametics_compact_example` and/or adding a comment at the top of the example file that explains where this solution is optimised for and, in case of speed, how much speedier it is. Maybe even why, so that not everybody has to reinvent the wheel.    
And/or add a readme to the dir, with that explanations and how to use them.  

Adding those explanations is of a 1/10 on the scale of urgency to me personally, so I'm also totally okay with closing this issue. (:rocket: to agree with closing without comments).
If any of the above is of higher urgency/importance to anyone, please tell us why. If not, let's follow @Insti 's suggestion and close the issue. 

As you may have noticed, this comment is also an experiment on how to make decisions together.  Without overlooking things that really matter to someone/anyone :-) and without adding things to our to do list that doesn't need to be there.  
If you love it or hate it or want to finetune, please let me know.

**Comment by petertseng** [comment]
Although I respectfully disagree (I believe that all solutions that are present should be run by CI, otherwise any of them that aren't run may go out of date), I am not the authority here; this is a situation where we will have to agree to disagree.
